### ISSUE TITLE
Change mouse cursor indicator during loading of a web page in Chrome 33 and later branches

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/phpdesktop#148]
Since Chrome 33 web pages do not show "loading cursor" in Google Chrome, it is Aura UI bug: https://code.google.com/p/chromium/issues/detail?id=133039

Change cursor icon in OnLoadingStateChange. See WM_SETCURSOR, GetCursor, SetCursor and LoadCursor on MSDN pages.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 28 Nov 2014 at 11:32

**Comment by cztomczak** [comment]
Fixed in commit 0b2a0148f6226857adbd3e30cb085006ca0f6488.
It's not perfect, but does its job pretty well.
