### ISSUE TITLE
Option for the Mongoose web server to listen on all available ip addresses (local and public)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/phpdesktop#165]
Mongoose allows to specify port-only to listen on and in such case the web server should be listening on all ip addresses available (127.0.0.1, 192.168.x.x, PUBLIC IP address). Example from mongoose docs: `listening_ports 8080,8043s` (the second port is for SLL and is optional). Currently phpdesktop forces a specific ip address be specified in settings.json. If the ip address is empty it assigns 127.0.0.1 by default. It should be allowed for the ip address to be "*" and in such case set the listening_ports option in mongoose to contain only port. Minor changes will be required in web_server.cpp:
* https://github.com/cztomczak/phpdesktop/blob/fa2ef7b1d63cbc9d1d117761123461baf798c385/phpdesktop-chrome47/web_server.cpp#L59
* https://github.com/cztomczak/phpdesktop/blob/fa2ef7b1d63cbc9d1d117761123461baf798c385/phpdesktop-chrome47/web_server.cpp#L161

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 23 Apr 2015 at 10:06

**Comment by dimasskt** [comment]
I'm thinking about work around this while this issue is not done.

Is there some known work around on it?

I am going to build a script that will set the ip of current machine to settings.json 
and run php-desktop.

**Comment by cztomczak** [comment]
Done in commit 4b000098dea8d95320867d96e7f52d43cb99dac2 . See it for more details.
