### ISSUE TITLE
Printing to PDF

### ISSUE THREAD

**Issue by onrozcn** [cztomczak/phpdesktop#167]
hi i use phpdesktop-chrome-39.0-php-5.4.33,

but i can't print to pdf my php page

**Comment by cztomczak** [comment]
Printing to PDF is supported in newer CEF versions. This will become available when we update CEF.

**Comment by agrapps** [comment]
Hi, im also trying to print, but i cant, whats CEF version?
Im actually using 
phpdesktop-master -47.5-rc-php-5.4.33

**Comment by cztomczak** [comment]
Can someone test it with latest phpdesktop v57?
https://github.com/cztomczak/phpdesktop/releases/tag/chrome-v57.0-rc

**Comment by ZanderBrown** [comment]
I've successfully used Microsoft Print to PDF from the print dialog using v57RC on WinX1607

[test.pdf](https://github.com/cztomczak/phpdesktop/files/862359/test.pdf)

**Comment by agrapps** [comment]
Hi cztomczak, i try it and it really print :)
I test it just with one button:
<input type="button" name="imprimir" value="Imprimir" onclick="window.print();">
Thanks a lot

**Comment by cztomczak** [comment]
Great :) Closing.

**Comment by shababhsiddique** [comment]
how can i enable the date time header on each page when printed? I cant seem to find that

**Comment by waelabohamza** [comment]
Print does not work in a program What is the solution I can use the latest version
