### ISSUE TITLE
Php Desktop for Mac?

### ISSUE THREAD

**Issue by moodooguru** [cztomczak/phpdesktop#169]
Would be great! Any chance we will see this happening soon?

**Comment by cztomczak** [comment]
Duplicate https://github.com/cztomczak/phpdesktop/issues/78

**Comment by svnpenn** [comment]
https://github.com/cztomczak/phpdesktop/issues/194

**Comment by svnpenn** [comment]
https://github.com/cztomczak/phpdesktop/issues/208

**Comment by timint** [comment]
First let me say thank you for this this nice project.
Is there any update on the Mac edition? I saw it was fully founded July last year.
