### ISSUE TITLE
Error on Visual Studio 2015

### ISSUE THREAD

**Issue by rubengc** [cztomczak/phpdesktop#170]
Hi, I have been followed all instructions to make the .exe file, but when I open the project file in VS 2015 I got an error about the project is using VS 2010 dependencies and It cannot be upgraded

How can I fix it?

**Comment by cztomczak** [comment]
As explained on https://code.google.com/p/phpdesktop/wiki/BuildOnWindows you can use either VS2010 or VS2013. The version of CEF library that we currently use may have some issues with VS2015 (but newer CEF will work ok). You can install multiple Visual Studio versions along with your VS2015 - the solution for now.

**Comment by ZanderBrown** [comment]
With #200 i assume that's fixed

**Comment by cztomczak** [comment]
Yeah, VS 2015 is now officially supported.
