### ISSUE TITLE
Chrome 47 RC

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#171]
CEF branch 2526.
Need to recheck issues that were discovered in Chrome 39 (Issue #146). Double mouse scrolling should be fixed in upstream CEF.

**Comment by zap0xfce2** [comment]
There is also a bug with jQuery UI Buttons rendering in CEF Branch 2171 (Chromium 39.0.2171.95) with CEF Branch 2272 (Chromium 41.0.2272.104) the rendering is okay again. When will PHPDesktop have greater than Chromium 39?

**Comment by cztomczak** [comment]
@zap0xfce2 Chrome 47 RC will be released in a few days.

**Comment by zap0xfce2** [comment]
Where can i download the PHP Desktop Chrome 47 binaries?

**Comment by cztomczak** [comment]
Issue is still Open.

**Comment by cztomczak** [comment]
Chrome 47 RC is ready.

Download: https://github.com/cztomczak/phpdesktop/wiki/Download-Chrome#release-candidates

I have tested only on Windows 7 SP1, but this release looks good and stable to me - bugs found in Chrome 39 RC are fixed eg. double scrolling is fixed.

Changes in d38c32a1607b026dac6c952545e17a5f081b8c05, c2bd8a49b69c0de24dfa001dcbfd21053b36a88b, dfb197e56d8805113e7517f45cd58eceda9688b0, b36fd350c9e2456ccfb495d97e7f7db75b13b3af, aa429a818f4174391b8d9b1f88f76320fa7b9e15.

Scanned with virustotal.com:
Detection ratio:	0 / 54
https://www.virustotal.com/en/file/be0a60ca31829d6c5cb7f494e53f993bea43bcfaeb3f07a94203ba393ff85a64/analysis/1455051440/

**Comment by 2braincells2go** [comment]
Not sure if appropriate place but like to report that everything looks good using Windows 10. Tried 47.0RC and now just 47.2RC and see no obvious issues.
