### ISSUE TITLE
How to add php extensions?

### ISSUE THREAD

**Issue by krembo** [cztomczak/phpdesktop#172]
I want in particular to enable php_opcache.dll extension.
I see that it was removed from the package because of some alerts, but is there any way to add and enable it?

**Comment by cztomczak** [comment]
You can replace PHP binaries, see instructions on the BuildOnWindows wiki page: https://github.com/cztomczak/phpdesktop/wiki/BuildOnWindows#download-php-binaries

**Comment by cztomczak** [comment]
Please ask questions on the Forum.

**Comment by krembo** [comment]
Thanks!
