### ISSUE TITLE
Migrate wiki pages from the wiki branch to the Wiki tab

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#173]
Work in progress.

**Comment by cztomczak** [comment]
Wiki pages are now fully functional: https://github.com/cztomczak/phpdesktop/wiki

The wiki branch was deleted. Use the Wiki tab to browse wiki pages now.

Attaching the python script that was used to fix wiki pages exported by Google Code:
[fix_markdown.zip](https://github.com/cztomczak/phpdesktop/files/120258/fix_markdown.zip)

**Comment by Narno** [comment]
:+1:
