### ISSUE TITLE
Custom user agent string

### ISSUE THREAD

**Issue by 2braincells2go** [cztomczak/phpdesktop#176]
Testing out the new RC Chrome RC 47 (working great so far).

I do not need heavy security as designing desktop apps for grade school users but, need to prevent them from accessing via browser. Make simple instruction software and some of the little boogers and smart enough to use browser:)

Even before RC47 attempted to use htaccess and restrict. Failed... Have read on stackoverflow and many other sites but never found working solution.

Do you know of good tutorial / working example for using htaccess?

Or am I wrong in thinking htaccess will work for my needs? IF wrong in my thinking, any input would be greatly appreciated.

**Comment by cztomczak** [comment]
Please ask questions on Forum.

**Comment by 2braincells2go** [comment]
my bad. what happens when you have 23 kids in one ear...
