### ISSUE TITLE
html select tag not work on phpdesktop-chrome-47.5-rc-php-5.4.33

### ISSUE THREAD

**Issue by hgati** [cztomczak/phpdesktop#185]
if always_on_top is true...........

settings.json
```json
"main_window": {
        "always_on_top": true,
},
```

www/index.php
```html
<select>
    <option>PHP Desktop 1</option>
    <option>PHP Desktop 2</option>
    <option>PHP Desktop 3</option>
    <option>PHP Desktop 4</option>
    <option>PHP Desktop 5</option>
    <option>PHP Desktop 6</option>
</select>
```

CAN'T DROP DOWN ~~

![snap1](https://cloud.githubusercontent.com/assets/6913728/13376085/bc5c74a4-ddf4-11e5-9de1-6c570321508c.png)

**Comment by cztomczak** [comment]
Already reported in Issue #182. Please report problems on the Forum.
