### ISSUE TITLE
Chrome v47 stable release with multiple php flavors: 5.4, 5.5, 5.6, 7.0

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#187]
Prepare a total of 4 zip packages. Do a quick test for each and scan with virustotal.com.

**Comment by zap0xfce2** [comment]
Is there a way to disable the internal WebServer (Mongoose) and just point to a web address?

**Comment by cztomczak** [comment]
@zap0xfce2 Ask questions on the Forum. You can do a redirect in index.php.

**Comment by ZanderBrown** [comment]
Should this be closed now in favour of #200

**Comment by cztomczak** [comment]
Yup :)
