### ISSUE TITLE
phpMyAdmin - Error

### ISSUE THREAD

**Issue by CGAP** [cztomczak/phpdesktop#192]
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): open(C:\Windows\TEMP\sess_ipiitudu0tlnlhom6nd4jfrcfn6ptbrq, O_RDWR) failed: Invalid argument (22)

Can anyone assist me to solve this issue?

In my php.ini file settings-  session.save_path="c:\temp\phpsessions"

**Comment by cztomczak** [comment]
Please retest with latest phpdesktop v57 with PHP 7.1. If reproduced I will reopen.
