### ISSUE TITLE
Where do I get the version for Mac?

### ISSUE THREAD

**Issue by DioneLago** [cztomczak/phpdesktop#194]
I liked the project, as did small tests, very good! But I tried to download a version of the same for Mac and have not found, there is only downloads with .exe, is there a version for Mac? If so, where meeting someone can help me?

**Comment by ZanderBrown** [comment]
You don't get it because it doesn't exist.

**Comment by cztomczak** [comment]
Only Windows platform is supported so far. Duplicate of #78 . There isn't much stopping from porting phpdesktop to Mac, only time and effort, all dependent libraries like Mongoose web server and Chromium Embedded Framework are supported on both Mac/Linux. Porting to Mac with basic settings support, without  all the advanced options from settings.json / js api, should be straightforward to do, in a matter of days I think. I have a Mac, but I don't use it too much, some day I may work on this port. Pull requests are welcome of course if someone would like to take this effort.

**Comment by DioneLago** [comment]
Guys, thanks for the clarification. If there is the possibility of a version for Mac and Linux would be perfect, PHP is a language for decades and is still very active in the market, I believe it would be possible to meet the demand for small business applications with simple solutions. @cztomczak congratulations here by made.

**Comment by carmenchapa** [comment]
Guys, this project seems awesome. So sad it is not supported by Mac. It would be really useful for me.

**Comment by svnpenn** [comment]
https://github.com/cztomczak/phpdesktop/issues/169

**Comment by svnpenn** [comment]
https://github.com/cztomczak/phpdesktop/issues/208

**Comment by cztomczak** [comment]
@s22-tech Current status on screenshot attached. Basically it works. Still a few things to fix before release.

![image](https://github.com/user-attachments/assets/a6f8dee1-9f5f-4d3f-8d78-a975e49125ce)
