### ISSUE TITLE
Minimize window and Auto stop features in settings.json file

### ISSUE THREAD

**Issue by monalisa21** [cztomczak/phpdesktop#198]
Hi,

I don't want the Main Window to show up while the application runs. But we don't have any options in the setting.json file to do that. I want my application run in the background or even showing minimized in tray is fine too. Also when application execution is completed can it be closed on its own.

Any help regarding the above issue, will be grateful.

Thanks!!

**Comment by cztomczak** [comment]
Please read this:
1. Do not create Issues to report problems and/or ask questions. Use the Forum for that.
2. Before creating an Issue it must first be discussed and confirmed on the Forum.
3. Always use the Forum: https://groups.google.com/d/forum/phpdesktop
