### ISSUE TITLE
Update to Chrome 57

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#200]
CEF prebuilt binaries now used are from Spotify automated builds: http://opensource.spotify.com/cefbuilds/index.html

Visual Studio 2015 is now used.

Requirements to run: Windows 7+.
Windows XP and Vista are no more supported.

Update to PHP 7.1.

PHP 7 requires vcruntime140.dll  - download [vc_redist.x86.exe](https://www.microsoft.com/en-us/download/details.aspx?id=48145) (13 MB).

Update [BuildOnWindows](https://github.com/cztomczak/phpdesktop/wiki/Build-on-Windows) wiki page.

**Comment by cztomczak** [comment]
57.0 RC released: https://github.com/cztomczak/phpdesktop/releases/tag/chrome-v57.0-rc

**Comment by ZanderBrown** [comment]
If it's only RC should it not be marked as a prerelease?

**Comment by cztomczak** [comment]
Yup :) Fixed.

**Comment by cztomczak** [comment]
Just for information, I just checked and there were 15412 downloads for the previous 47.5 release.

**Comment by JeanPaulLucien** [comment]
I'm disappointed that new phpdesktop versions do not work in Windows XP.
