### ISSUE TITLE
How to use webcam

### ISSUE THREAD

**Issue by agrapps** [cztomczak/phpdesktop#202]
Hi, is there a way to use webcam in my app, im using webcam.js, it works on localhost but not in phpdesktop it sends me this: 

Javascript Alert - http://127.0.0.1:55365
Webcam.js Error: Could not access to webcam:
PermissionDeniedError: [Object NavigatorUserMediaError]

Thanks

**Comment by agrapps** [comment]
Already could, i found the soultion here:
https://github.com/cztomczak/phpdesktop/wiki/Chrome-settings#command_line_switches

In settings.json it have to be like this:

"command_line_switches": {
            "enable-media-stream": true
        },

**Comment by cztomczak** [comment]
Please do not create issues on github. Use Forum to report issues.
