### ISSUE TITLE
Enable To Attach Database With Php Script

### ISSUE THREAD

**Issue by ahmedilyasofficial** [cztomczak/phpdesktop#204]
Hi PHP desktop,

I Am Very Happy This Is Very Good Tool For Creating Desktop Application When i Want To Attach Database In My Php Application Using PHPMyAdmin I try All Common Pass Like Root, admin pass, Naz etc. Also, I Use SQL Lite and Attach It's Not Work Please Tell Me The Solution What is The Username and Pass How I can Access Phpmyadmin.

Problem Image Source.
http://prntscr.com/fde33s
http://prntscr.com/fde3zf

I am Very Thanked Full To I Really Want To Know How I Can Do Please Help and Tell Me The Solution.
Thanks,
Ahmed.

**Comment by cztomczak** [comment]
Please ask questions on the Forum.
