### ISSUE TITLE
display_errors = Off

### ISSUE THREAD

**Issue by flourigh** [cztomczak/phpdesktop#205]
Hello i have a problem with a display_errors parameters in PHP.INI on change to OFF this app crash.

**Comment by doublevie** [comment]
Try with value 0

**Comment by cztomczak** [comment]
Please ask questions on the Forum.

**Comment by flourigh** [comment]
this error
https://prntscr.com/ffqun7
https://prntscr.com/ffqvcr
https://prntscr.com/ffqun9
https://prntscr.com/ffqun8
https://prntscr.com/ffqunj

http://imgur.com/a/BlX1s

**Comment by ZanderBrown** [comment]
Instead of hiding the errors you should be working on fixing them

**Comment by flourigh** [comment]
@ZanderBrown if($Var) { // with value } elser { $var = value; } and it breaks when doing so, it's not my fault. ...


If you do not have constructive words, insert the ...

**Comment by flourigh** [comment]
exemple i trying this error

`	if(!$_COOKIE[SITEINDEX]) {
	    setcookie(SITEINDEX, max(explode('/', dirname($_SERVER[PHP_SELF]))));
	    define(siteindex, '/' . max(explode('/', dirname($_SERVER[PHP_SELF]))) . '/');
    } else {
    	define(siteindex, '/' . $_COOKIE[SITEINDEX] . '/'); }`

**Comment by cztomczak** [comment]
Please ask general PHP questions on a general PHP forum. Locking this conversation.
