### ISSUE TITLE
External page won't loaded in new window

### ISSUE THREAD

**Issue by penggunaphp** [cztomczak/phpdesktop#213]
In PHPDesktop i open link whi target="_blank" the external page won't loaded...

![image](https://user-images.githubusercontent.com/11702917/30289758-5e621d72-9757-11e7-9cd2-00344f1d6909.png)

But with firefox it works fine... 

![image](https://user-images.githubusercontent.com/11702917/30289774-68ef5cc8-9757-11e7-95ca-10f96fba2823.png)

How can i fix this? thank 

Sorry i create new issue in here, I search everywhere and i'm stuck... thank you...

**Comment by cztomczak** [comment]
Please report problems on the forum.
