### ISSUE TITLE
Multiple CGI/FastCGI Processes Running in the Background

### ISSUE THREAD

**Issue by jakecorn** [cztomczak/phpdesktop#216]
Hi guys,

Please help me regarding with this problem.
I am implementing ajax request for every 1 second around 3 requests every second, these run in the background. But the problem is,  there are times that the Http request status is always pending, the request doesn't get any response from the server. Once there is one occurrence of pending status, all of the following request will be pending too. I found out that this happens only when the CGI/FastCGI is not closed automatically in the Task Manager. In normal condition, it only shows 1 CGI/FastCGI in the task manager , but when the problem mention above starts to occur, I noticed that it shows multiple processes of CGI/FastCGI in the task manager and never ended.  What I did is to close all  the current processes of CGI/FastCGI manually in the task manager that is the time that I got a response in the new request, the old request will be canceled, then everything will be fine. But after several minutes, the problem will occur again.

Please help me, thanks.

**Comment by cztomczak** [comment]
Please report problems on the Forum. This may be an issue with your PHP script.

**Comment by jakecorn** [comment]
@cztomczak, what do you mean? To what forum should I report the problem?.I added an image on the details

**Comment by cztomczak** [comment]
See https://goo.gl/ppizK3

**Comment by jakecorn** [comment]
@cztomczak the link is block in our network.

**Comment by cztomczak** [comment]
https://groups.google.com/forum/#!forum/phpdesktop

**Comment by jakecorn** [comment]
@cztomczak, thanks for your reply

**Comment by jakecorn** [comment]
the second link is still blocked in our network.
