### ISSUE TITLE
How to set PHP session.gc_maxlifetime value

### ISSUE THREAD

**Issue by jakecorn** [cztomczak/phpdesktop#217]
Good day!

Please help how to set the value for variable  session.gc_maxlifetime because in the default configuration found in php.ini there is no such variable. Is it okay to add new variable? What is the default value of that variable?

Please help me.

Thank you

**Comment by cztomczak** [comment]
Please ask questions on the Forum: https://goo.gl/ppizK3
It's okay to add a new variable. Look in PHP documentation for the default value.
