### ISSUE TITLE
How can i use my online server in application.

### ISSUE THREAD

**Issue by shrikant190890** [cztomczak/phpdesktop#218]
i have converted my laravel website into destop application using phpdesktop. Its working fine on localhost. Now i want to connect it to my live server (Means i want to get all time data from live server and if i do some changes it will store them on server. ).
Is this is possible?

**Comment by ZanderBrown** [comment]
1: Not the right place
2: Have you tried to do it?

**Comment by juangacovas** [comment]
Make your remote mysql accept external connections, not only from
localhost, usually from a new mysql user for that purpose. Then change the
host, user and password config for mysql in your laravel app.

Hope that helps

**Comment by shrikant190890** [comment]
yes i have tried it with ip address in listen_on option but on other system it threw error  on start of application.
