### ISSUE TITLE
there is no phpdesktop_chrome.exe file in it

### ISSUE THREAD

**Issue by asmarfaq** [cztomczak/phpdesktop#220]
Please read this:
1. Do not create Issues to report problems and/or ask questions. Use the Forum for that.
2. Before creating an Issue it must first be discussed and confirmed on the Forum.
3. Always use the Forum: https://groups.google.com/d/forum/phpdesktop

**Comment by ZanderBrown** [comment]
Support is given on the forum, this is for bugs.


[Have you downloaded a release](https://github.com/cztomczak/phpdesktop/wiki/Download-Chrome) or did you just clone the repository

**Comment by cztomczak** [comment]
Like ZanderBrown says, looks like you've downloaded sources instead of binaries.
