### ISSUE TITLE
Source code protection for PHP 7

### ISSUE THREAD

**Issue by jirehnimes** [cztomczak/phpdesktop#222]
Since you updated the chrome57 with PHP7, don't you have any source code protection for it? Thanks.

https://github.com/cztomczak/phpdesktop/wiki/Source-code-protection

**Comment by cztomczak** [comment]
See https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#how-do-i-protect-php-sources-in-the-www-directory

Please ask questions on the Forum.

**Comment by jirehnimes** [comment]
Sorry about that I haven't read a different guide. Thanks very much and for fast reply.

**Comment by jirehnimes** [comment]
Actually before reading this I'm actually trying the ColdevProLayer.

**Comment by swarda-master** [comment]
I recommend Enigma Virtual Box: https://enigmaprotector.com/en/aboutvb.html
