### ISSUE TITLE
Suggestions for PHPDesktop

### ISSUE THREAD

**Issue by astherweb** [cztomczak/phpdesktop#224]
Hi,

Congratulations for the initiative. I'm doing some testing and I really like the system.
I do not know how to program in C otherwise it could contrinuir with the suggestions that I will mention.

1) The settings allow changing color of the window, so not only stay in the windows default. Use colors that match the system layout (eg Spotfy desktop, Adobe ...).

2) Open browser tabs.

Thanks

**Comment by cztomczak** [comment]
Custom window themes are to be implemented in Issue #26. Regarding browser tabs - I think that's something you could implement using html5 frames. It's best to keep such discussions on the Forum.
