### ISSUE TITLE
.mp4 Video Support

### ISSUE THREAD

**Issue by c11media** [cztomczak/phpdesktop#228]
We are trying to move a web app, essentially its a webpage with a video playing on a muted autoplay loop. I saw support in PHP Desktop for extra mime types and modified as below however the area is blank as if it is unsupported and when i try a video.js player it says there is no compatible source for this media. With the web version there are  no issues using remote and local media file. 

I added the "extra_mime_types": ".mp4=video/mp4" to the settings.json under web server and added  "command_line_switches": {
		"enable-media-stream": "",
to the chrome settings. 

Does PHPD support video playbacck as chrome does nativly?

**Comment by cztomczak** [comment]
Please do not create issues in the tracker. Ask for help on the Forum.

**Comment by samjco** [comment]
Hey @cztomczak 
Couldn't we use ffmpeg (https://ffmpeg.org/download.html)
To convert Mp4 to WebM which works with phpdesktop?

```
<?php
$folder = '/path/to/uploads/folder';
$filename = 'your_video.mp4';
$newFilename = pathinfo($filename, PATHINFO_FILENAME).'.webm';

exec('/usr/bin/ffmpeg -y -i '.$folder.DIRECTORY_SEPARATOR.$filename.' -c:v libx264 -c:a aac -pix_fmt yuv420p -movflags faststart -hide_banner '.$folder.DIRECTORY_SEPARATOR.$newFilename.' 2>&1', $out, $res);

if($res != 0) {
    error_log(var_export($out, true));
    error_log(var_export($res, true));

    throw new \Exception("Error!");
}
?>
```
