### ISSUE TITLE
php extension number change when try to upload file

### ISSUE THREAD

**Issue by golches** [cztomczak/phpdesktop#230]
i try to use phpdesktop to upload images and video, and i use file input plugin, but when i click on file input plugin to choose files i noticed that the number of extension change from 40 to 28, all extension in the php.in are unloaded, and if i close the file browser without choosing file, the number of extension back to 40, but if select a file the number of extension stay to 28, and all extension in the php.ini not loaded, pliz help me

thank you

**Comment by cztomczak** [comment]
Please ask questions on the Forum. I saw your post, but I don't quite understand your problem. Provide more details on the Forum.
