### ISSUE TITLE
sessions not working

### ISSUE THREAD

**Issue by kasunubeysekara** [cztomczak/phpdesktop#232]
Warning: session_start(): Cannot send session cookie - headers already sent by (output started at E:\phpdesktop-chrome-31.8-php-5.6.1\www\dfd\salesreport.php:2) in E:\phpdesktop-chrome-31.8-php-5.6.1\www\dfd\session.php on line 5

**Comment by cztomczak** [comment]
Your problem is PHP related and you should ask for help on a general PHP forum.

**Comment by n-ice-ch** [comment]
The issue is related by the php.ini delivered by this great project.
Simply add those lines in your php.ini and the issues with php session handling are gone:
```
; = Session
session.save_path = ""
session.use_cookies = 1 
session.name = PHPSESSID
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.serialize_handler = php
```
