### ISSUE TITLE
question about --plugin-path parameter

### ISSUE THREAD

**Issue by YopSolo** [cztomczak/phpdesktop#233]
When i launch my test app i see this line in the log

- 15:05:13.000 DEBUG: Command line string for the plugin process: "F:\tests\desktop-chrome\phpdesktop-chrome.exe" --type=plugin --plugin-path="C:\WINDOWS\SysWOW64\Macromed\Flash\NPSWF32_27_0_0_183.dll" --no-sandbox --lang=en-US --channel="5752.2.1346258657\173404711" --lang=en-US --log-file="F:\tests\desktop-chrome\debug.log" /prefetch:-390060480

is there a way to override this path --plugin-path="C:\WINDOWS\SysWOW64\Macromed\Flash\NPSWF32_27_0_0_183.dll"
?

maybe in the settings.json but i don't find any documentation

**Comment by YopSolo** [comment]
after another look to the documentation i see the  "command_line_switches": {} in settings

i have tested like this
        "command_line_switches": {
            "lang": "fr",
            "plugin-path":"/plugin/NPSWF32_27_0_0_183.dll"
        },
and 
        "command_line_switches": {
            "lang": "fr",
            "plugin-path":"F:\\RT\\_a tester\\ToDesktop\\desktop-chrome\\plugin\\NPSWF32_27_0_0_183.dll"
        },

in log i see this line
- 15:56:54.000 DEBUG: Command line string for the browser process: "F:\RT\_a tester\ToDesktop\desktop-chrome\test.exe" --lang=en-US --log-file="F:\RT\_a tester\ToDesktop\desktop-chrome\debug.log" --remote-debugging-port=53426 --no-sandbox --lang=fr --plugin-path="F:\RT\_a tester\ToDesktop\desktop-chrome\plugin\NPSWF32_27_0_0_183.dll"

but the --plugin-path is ignored and it load 
C:\WINDOWS\SysWOW64\Macromed\Flash\NPSWF32_27_0_0_183.dll

(verified if renamed to C:\WINDOWS\SysWOW64\Macromed\Flash\_NPSWF32_27_0_0_183.dll)

**Comment by cztomczak** [comment]
Please ask questions on the Forum and provide phpdesktop version information.
