### ISSUE TITLE
JavaScript file Path

### ISSUE THREAD

**Issue by reinaldoacosta** [cztomczak/phpdesktop#243]
For those planning doing bigger operations with this, there's a reason why I abandoned this thing, in Electron you have the option to open a file from the file system, for those of you that know Javascript, you guys should know that in javascript you cannot access for example a javascript absolute path, if I'm not mistaken you get something like C:\fakepath\file.png <-- and you can use this with the readFile API, but you cannot read its absolute path, and you won't be able to do much with this if you need the path of certain file.

Let's say you want to build a code editor, or you want to modify a file and save the changes, you will be able to get that index.php file but you won't get that C:\Windows\Users\Mike\Documents\www\index.php path, you'll get C:\fakepath\index.php so your PHP won't know where it will write the file to.

It's necessary that we have access to files absolute path

![filepath](https://user-images.githubusercontent.com/12644557/52510667-4bb8b200-2bd3-11e9-8069-08ad4384f912.png)

**Comment by oneinazillion** [comment]
In PHP  ` "$_SERVER[DOCUMENT_ROOT]" ` gives you the actual path of the 'www' folder  :
` "$_SERVER[DOCUMENT_ROOT]" . "/path/to/your/resource/" `
 
In Electron, ` __dirname ` has the same effect : 
` __dirname + "/path/to/your/resource/" `

**Comment by oneinazillion** [comment]
Also, I love phpdesktop! It gives you the easiest and most versatile way of implementing your PHP project in a desktop environment. My only problem with it is that it's very slow to read and write SQLite data when compared to third party node packages for the same in Electron. "better-sqlite3" is an npm package that reads and writes magnitudes faster than PHP 7.

**Comment by reinaldoacosta** [comment]
> In PHP `"$_SERVER[DOCUMENT_ROOT]"` gives you the actual path of the 'www' folder :
> `"$_SERVER[DOCUMENT_ROOT]" . "/path/to/your/resource"`
> 
> In Electron, `__dirname` has the same effect :
> `__dirname + "/path/to/your/resource"`

I think you did not understand, what I'd like to get is the path of a file gotten through a file input in the browser view.

**Comment by cztomczak** [comment]
What you're trying to achieve is possible with PHP Desktop and it is quite easy. In PHP Desktop you have full access to the filesystem in PHP scripts and you can replace the native "Choose file" dialog with your own custom implementation using PHP and js/jquery scripting. You could reuse or base your code on some existing PHP library that allows you to browse files, see: https://www.google.com/search?q=php+filesystem+browser . Or just do something simple, I think implementing a custom "Choose file" dialog with jquery and PHP is a matter of a few hours.

Please discuss things on the Forum.
