### ISSUE TITLE
Can you release mongoose as a separate app?

### ISSUE THREAD

**Issue by Leandro-Reis** [cztomczak/phpdesktop#248]
Testing PhpDesktop i realise that it doesn't open a firewall window as apache. It would be nice if you also offered your mongoose version as a separate application for projects that only need the server.

![Image](http://www.leftycoder.com/wp-content/uploads/2014/03/XAMPPFirewallMessageOnStart.jpg)

**Comment by cztomczak** [comment]
Please ask questions on the forum or on stackoverflow tagged 'phpdesktop'.
