### ISSUE TITLE
Cannot send session cache limiter 

### ISSUE THREAD

**Issue by Umarnisar** [cztomczak/phpdesktop#249]
Every thing is fine but showing this error bellow.

**Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at E:\phpdesktop-chrome-57.0-rc-php-7.1.3\www\sims\includes\load.php:2) in E:\phpdesktop-chrome-57.0-rc-php-7.1.3\www\sims\includes\load.php on line 3**

this code is running fine on XAMPP Server

**Comment by cztomczak** [comment]
The error message is self explanatory and tells you where to look to resolve the issue. This is an issue with PHP and you should ask for help on a general PHP forum.

**Comment by n-ice-ch** [comment]
The issue is related by the php.ini delivered by this great project.
Simply add those lines in your php.ini and the issues with php session handling are gone:
```
; = Session
session.save_path = ""
session.use_cookies = 1 
session.name = PHPSESSID
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.serialize_handler = php
```
