### ISSUE TITLE
Openssl support in PHP binaries on Linux

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#250]
When running Laravel application on Linux you get this error:
```
Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length()
```

It is caused because openssl support is missing.

**Comment by cztomczak** [comment]
Commits 60520b83fe1fbccd1a074d28d9befbbf787c8494 and 53c27e3 add openssl support in the `build-php-with-ext.sh` script.

To resolve the issue with current phpdesktop 72.1 binaries you have to run the `build-php-with-ext.sh` script to build PHP with openssl support and then replace the PHP binaries in your phpdesktop folder:
1. Copy "build/bin/php-cgi-with-ext" binary to the "phpdesktop/" directory
2. Update "settings.json" file,  "web_server" > "cgi_interpreter" option to point to the "php-cgi-with-ext" binary (or just replace the old "php-cgi" with the new "php-cgi-with-ext" binary).

**Comment by tonitegarsahidi** [comment]
thanks @cztomczak , 
today I found the same issues when try to move my laravel 5.7 app to phpdesktop, 
then found this thread.
after download the "php-cgi-with-ext" files, then update the "settings.json" as mentioned above, but then the error changes to 
`"Error 500: Internal Server Error. CGI program sent malformed or too big (>16384 bytes) HTTP headers"
`no more error message mentioned on the browser, but then after seeing the console, I found one line of log console 

> "[0109/103351.596669:ERROR:mongoose_server.cpp(31)] spawn_process: execle(/home/..../phpdesktop/php-cgi-with-ext index.php): Permission denied"

I found that, after copying the php-cgi-with-ext, the file permission isn't set yet for executing. After quick chmod, then re run the apps, the apps works like a charm!

I hope this thread helps other who stuck on the same problem.

**Comment by vipertecpro** [comment]
Alright I got this one, this was the issue i was facing
```

[0112/230346.700818:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
/opt/lampp/htdocs/laracef/php-cgi-with-ext: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[0112/230346.728774:INFO:mongoose_server.cpp(52)] GET 500 /
```
Resolved by download/installing https://packages.debian.org/jessie/amd64/libssl1.0.0

I'm running laravel Laravel Framework 6.10.1, here is the screenshot of it

![Screenshot from 2020-01-12 23-10-09](https://user-images.githubusercontent.com/11619188/72223010-bc5d1100-3590-11ea-97ef-2f6b8aba4d67.png)

**Comment by vipertecpro** [comment]
> How do i run the "build-php-with-ext.sh" script for phpdesktop-linux-72.1
> the script does not even exist in the package!

I think what he meant is 
1. Download [php-cgi-with-ext ](https://github.com/cztomczak/phpdesktop/releases/download/linux-v72.0/php-cgi-with-ext)
2. Open settings.json on the root 
` "cgi_interpreter": "php-cgi-with-ext",`

Here is the screenshot
![Screenshot from 2020-01-12 23-15-01](https://user-images.githubusercontent.com/11619188/72223088-73598c80-3591-11ea-84e5-5e0c90e4219e.png)

**Comment by cztomczak** [comment]
Added "PHP on Linux doesn't support XXX extension" section on the Knowledge-Base wiki page: https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#php-on-linux-doesnt-support-xxx-extension

**Comment by Darkhackit** [comment]
Also facing the same problem on windows
Please how do i solve it

**Comment by Darkhackit** [comment]
> 
> 
> When running Laravel application on Linux you get this error:
> 
> ```
> Call to undefined function Illuminate\Encryption\openssl_cipher_iv_length()
> ```
> 
> It is caused because openssl support is missing.

Please am facing the same problem on windows

**Comment by ashu-ch** [comment]
after replacing php-cgi with php-cgi-with-ext I'm getting this error

Error 500: Internal Server Error
CGI program sent malformed or too big (>16384 bytes) HTTP headers: []

**Comment by cztomczak** [comment]
See https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#error-500-internal-server-error-cgi-program-sent-malformed-or-too-big-16384-bytes-http-headers

Test run php-cgi-with ext with a simple script from command line.

**Comment by cztomczak** [comment]
You have to replace all PHP binaries, not just one file.

**Comment by cztomczak** [comment]
Nvm before. Test run the new built "php-cgi" with your script from command line.

**Comment by ashu-ch** [comment]
[0515/174645.672717:ERROR:block_files.cc(111)] Failing CreateMapBlock
[0515/174645.674348:ERROR:backend_impl.cc(605)] Create entry failed http://127.0.0.1:33789/
[0515/174645.677002:INFO:mongoose_server.cpp(52)] GET 500 /

[0515/174645.704347:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[0515/174645.722479:ERROR:command_buffer_proxy_impl.cc(124)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.

this is in debug.log

**Comment by ashu-ch** [comment]
@cztomczak 
if I'm uninstalling php from my system my app is not running.
if I've to install php in my system then what is the use of php directory
