### ISSUE TITLE
Cannot spawn CGI process : Any fix ?

### ISSUE THREAD

**Issue by ajayreddy28390** [cztomczak/phpdesktop#251]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

with phpdesktop-chrome-57.0-rc-php-7.1.3

Error 500: Internal Server Error
Cannot spawn CGI process [C:\student\www/index.php]: No such device or address

Debug output:
- 13:16:43.047 INFO: Started application
- 13:16:43.047 INFO: Logging to: C:\student\debug.log
- 13:16:43.047 INFO: Log level = DEBUG4
- 13:16:43.063 INFO: Starting Mongoose 3.9c web server
- 13:16:43.063 INFO: WWW directory: C:\student\www
- 13:16:43.063 INFO: Index files: index.html,index.php
- 13:16:43.063 INFO: CGI interpreter: C:\student\php\php-cgi.exe
- 13:16:43.063 INFO: CGI pattern: **.php$
- 13:16:43.063 INFO: Hide files patterns: 
- 13:16:43.063 INFO: CGI environment variables set: TMP=C:\Users\ajayr\AppData\Local\Temp\,TEMP=C:\Users\ajayr\AppData\Local\Temp\,TMPDIR=C:\Users\ajayr\AppData\Local\Temp\,SERVER_NAME=127.0.0.1,PHPDESKTOP_VERSION=57.0
- 13:16:43.063 INFO: Web server url: http://127.0.0.1:64778/
- 13:16:43.063 INFO: remote_debugging_port = 57806
- 13:16:43.063 DEBUG: Command line string for the browser process: "C:\student\phpdesktop-chrome.exe" --no-sandbox --lang=en-US --log-file="C:\student\debug.log" --remote-debugging-port=57806
- 13:16:43.110 DEBUG: App::OnContextInitialized()
- 13:16:43.110 DEBUG: Window max width/height = 1840/1112
- 13:16:43.110 DEBUG: GetBrowserWindow(): not found, hwnd = 6686238
- 13:16:43.110 DEBUG: WindowProc(): event WM_GETMINMAXINFO: could not fetch BrowserWindow
- 13:16:43.110 DEBUG: BrowserWindow::CreateBrowserControl()
- 13:16:43.110 DEBUG: StoreBrowserWindow(): hwnd = 6686238
- 13:16:43.141 DEBUG: ClientHandler::OnAfterCreated()
- 13:16:43.141 DEBUG: SetCefBrowser() called in ClientHandler::OnAfterCreated()
- 13:16:43.000 DEBUG: Command line string for the gpu-process process: "C:\student\phpdesktop-chrome.exe" --type=gpu-process --no-sandbox --lang=en-US --log-file="C:\student\debug.log" --disable-direct-composition --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,18,19,20,23,41,61,74 --disable-gl-extensions="GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent" --gpu-vendor-id=0x8086 --gpu-device-id=0x5912 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=26.20.100.6859 --gpu-driver-date=4-30-2019 --lang=en-US --log-file="C:\student\debug.log" --service-request-channel-token=3A349CB8C55026328EE0EE8BB3B3D1A4 --mojo-platform-channel-handle=1808 /prefetch:2
- 13:16:43.141 DEBUG: OnLoadingStateChange: loading=1, url=
- 13:16:43.000 DEBUG: Command line string for the renderer process: "C:\student\phpdesktop-chrome.exe" --type=renderer --no-sandbox --primordial-pipe-token=C59D3AD31486BE998F5C3D401A75D71D --lang=en-US --lang=en-US --log-file="C:\student\debug.log" --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --service-request-channel-token=C59D3AD31486BE998F5C3D401A75D71D --renderer-client-id=3 --mojo-platform-channel-handle=2328 /prefetch:1
[0618/131643.662:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
- 13:16:43.031 DEBUG: OnBrowserCreated()
- 13:16:47.578 WARNING: spawn_process: CreateProcess(C:\student\php\php-cgi.exe "C:\student\www\index.php"): 2
- 13:16:47.578 INFO: GET 500 /
- 13:16:47.610 DEBUG: OnLoadingStateChange: loading=0, url=http://127.0.0.1:64778/
- 13:26:47.062 INFO: --------------------------------------------------------
- 13:26:47.062 INFO: Started application
- 13:26:47.062 INFO: Logging to: C:\student\debug.log
- 13:26:47.062 INFO: Log level = DEBUG4
- 13:26:47.062 INFO: Starting Mongoose 3.9c web server
- 13:26:47.062 INFO: WWW directory: C:\student\www
- 13:26:47.062 INFO: Index files: index.html,index.php
- 13:26:47.062 INFO: CGI interpreter: C:\student\php\php-cgi.exe
- 13:26:47.062 INFO: CGI pattern: **.php$
- 13:26:47.062 INFO: Hide files patterns: 
- 13:26:47.062 INFO: CGI environment variables set: TMP=C:\Users\ajayr\AppData\Local\Temp\,TEMP=C:\Users\ajayr\AppData\Local\Temp\,TMPDIR=C:\Users\ajayr\AppData\Local\Temp\,SERVER_NAME=127.0.0.1,PHPDESKTOP_VERSION=57.0
- 13:26:47.062 INFO: Web server url: http://127.0.0.1:65316/
- 13:26:47.062 INFO: remote_debugging_port = 51260
- 13:26:47.062 DEBUG: Command line string for the browser process: "C:\student\phpdesktop-chrome.exe" --no-sandbox --lang=en-US --log-file="C:\student\debug.log" --remote-debugging-port=51260
- 13:26:47.109 DEBUG: App::OnContextInitialized()
- 13:26:47.109 DEBUG: Window max width/height = 1840/1112
- 13:26:47.109 DEBUG: GetBrowserWindow(): not found, hwnd = 2688382
- 13:26:47.109 DEBUG: WindowProc(): event WM_GETMINMAXINFO: could not fetch BrowserWindow
- 13:26:47.109 DEBUG: BrowserWindow::CreateBrowserControl()
- 13:26:47.109 DEBUG: StoreBrowserWindow(): hwnd = 2688382
- 13:26:47.000 DEBUG: Command line string for the gpu-process process: "C:\student\phpdesktop-chrome.exe" --type=gpu-process --no-sandbox --lang=en-US --log-file="C:\student\debug.log" --disable-direct-composition --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,18,19,20,23,41,61,74 --disable-gl-extensions="GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent" --gpu-vendor-id=0x8086 --gpu-device-id=0x5912 --gpu-driver-vendor="Intel Corporation" --gpu-driver-version=26.20.100.6859 --gpu-driver-date=4-30-2019 --lang=en-US --log-file="C:\student\debug.log" --service-request-channel-token=CB74E161079187ADD089A59A59927DA0 --mojo-platform-channel-handle=1800 /prefetch:2
- 13:26:47.140 DEBUG: ClientHandler::OnAfterCreated()
- 13:26:47.140 DEBUG: SetCefBrowser() called in ClientHandler::OnAfterCreated()
- 13:26:47.140 DEBUG: OnLoadingStateChange: loading=1, url=
[0618/132647.923:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
- 13:26:47.000 DEBUG: Command line string for the renderer process: "C:\student\phpdesktop-chrome.exe" --type=renderer --no-sandbox --primordial-pipe-token=AA8E2D1EF36E4FFA12239F5EED6D3D3C --lang=en-US --lang=en-US --log-file="C:\student\debug.log" --enable-pinch --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --service-request-channel-token=AA8E2D1EF36E4FFA12239F5EED6D3D3C --renderer-client-id=3 --mojo-platform-channel-handle=2400 /prefetch:1
- 13:26:47.031 DEBUG: OnBrowserCreated()
- 13:26:51.578 WARNING: spawn_process: CreateProcess(C:\student\php\php-cgi.exe "C:\student\www\index.php"): 2
- 13:26:51.578 INFO: GET 500 /
- 13:26:51.594 DEBUG: OnLoadingStateChange: loading=0, url=http://127.0.0.1:65316/
- 13:29:33.250 DEBUG: WM_DESTROY
- 13:29:33.250 DEBUG: RemoveBrowserWindow(): hwnd = 2688382
- 13:29:33.250 INFO: Stopping Mongoose web server
- 13:29:33.250 DEBUG: Mongoose webserver stopped immediately
- 13:29:33.250 DEBUG: OnBeforeClose() hwnd=2359360
- 13:29:33.250 DEBUG: RemoveBrowserWindow(): hwnd = 2359360
- 13:29:33.250 DEBUG: GetBrowserWindow(): not found, hwnd = 2359360
- 13:29:33.250 WARNING: RemoveBrowserWindow() failed: GetBrowserWindow() failed
- 13:29:33.250 DEBUG: Calling CefQuitMessageLoop()
- 13:29:33.078 DEBUG: OnBrowserDestroyed()
- 13:29:34.265 INFO: Ended application
- 13:29:34.265 INFO: --------------------------------------------------------

**Comment by cztomczak** [comment]
What OS? Does it work if you run original phpdesktop binaries not modified in any way? (no changes to configuration or www/ directory or anything).

**Comment by ajayreddy28390** [comment]
Win 10
It works for me over phpdesktop but mariadb SQL unable to connect.

My goal is to get executable file for php/mysql website.

**Comment by cztomczak** [comment]
Please ask questions on the forum.

Check if binary files are not missing (php/php-cgi.exe). Also check if PHP startups successfully, see:
https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#problem-running-php-script

**Comment by zlatsal** [comment]
https://github.com/cztomczak/phpdesktop/issues/68

It's probably this unicode issue which described at this link. It worked for me.
