### ISSUE TITLE
how can I let everyone in a LAN use my app

### ISSUE THREAD

**Issue by icy2003** [cztomczak/phpdesktop#252]
```
"listen_on": ["192.168.0.106", 2003],
```
this is my config for now, but my LAN ip always change, I tried '0.0.0.0' but no use……

**Comment by cztomczak** [comment]
You would have to configure your LAN ip to be fixed and then use that ip in phpdesktop settings.

**Comment by cztomczak** [comment]
Actually you can set ip address to "*" and it will listen on all ip addresses. See documentation:
https://github.com/cztomczak/phpdesktop/wiki/Settings#listen_on

**Comment by icy2003** [comment]
@cztomczak it works thank you
