### ISSUE TITLE
Linux: Support building PHP with curl extension

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/phpdesktop#253]
Issue reported by @phpengine on the forum:
https://groups.google.com/d/topic/phpdesktop/pXhpQ72KHgA/discussion

**Comment by cztomczak** [comment]
Done in rev dea1e23.

**Comment by cztomczak** [comment]
Added "PHP on Linux doesn't support XXX extension" section on the Knowledge-Base wiki page: https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#php-on-linux-doesnt-support-xxx-extension

**Comment by Dr-Nio** [comment]
How do i fix this error
Fatal error: Uncaught Error: Call to undefined function curl_init()
PHPDESKTOP_VERSION=31.8

**Comment by Dr-Nio** [comment]
> 
> 
> How do i fix this error
> Fatal error: Uncaught Error: Call to undefined function curl_init()
> PHPDESKTOP_VERSION=31.8

I solved this problem by enabling 
FROM
;extension_dir = "ext"
TO
extension_dir = "ext"

In php.ini file 
PHP7.6.14

Enjoy!
