### ISSUE TITLE
Limitation of Phpdesktop

### ISSUE THREAD

**Issue by paramesharobit** [cztomczak/phpdesktop#254]
Can we develop screen recording, audio, video recording using this platform? Please let me know if it is possible or not so that I may proceed further.

**Comment by cztomczak** [comment]
To enable WebRTC features (microphone/camera recording, screen capturing) pass the `--enable-media-stream` switch. See the ChromSettings wiki page.

**Comment by cztomczak** [comment]
Note that currently PHP Desktop embeds Chrome v57 on Windows and Chrome v72 on Linux. So any limitations of Chrome version apply.

**Comment by paramesharobit** [comment]
Thank you very much @cztomczak for your reply. But how user can enable chrome extension inside the desktop application ? Because screen capture will not work except if we use webrtc.

**Comment by cztomczak** [comment]
Extensions support is limited. Extensions and WebRTC are two different things. I suggest you find some tutorials on the web.
