### ISSUE TITLE
Disable the close button or minimize in system tray on close button click

### ISSUE THREAD

**Issue by anupambd94** [cztomczak/phpdesktop#256]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

I want to minimize in the system tray the software built with PHP Desktop Chrome when the close button is pressed. I do not want to allow to close the main window. Is there any way to do that so?
if not then i want to hide or disable the close button as like we can easily disable the maximize button in PHP Desktop Chrome Application. Please, can anyone help me?

**Comment by cztomczak** [comment]
Such feature is not supported. Related: #26, #31, #95.

**Comment by KevinWoolfolk** [comment]
Do you find any solution for the problem?
