### ISSUE TITLE
Cmake Error: Cmake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PRGORAM is not set

### ISSUE THREAD

**Issue by Jalpa-Ahalpara** [cztomczak/phpdesktop#257]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

I get error for perform Build cefclient and copy CEF files to phpdesktop
after step 4 when run command of step 5 (Execute cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DUSE_SANDBOX=OFF ..)

I use visual studio 2015 
c++

get this error 
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "cef_binary/build/CMakeFiles/CMakeOutput.log".

Any solution For This 

Thanks In Advance

**Comment by cztomczak** [comment]
You have to read carefully the build instructions and follow all of the instructions. You have to download ninja program and put it in PATH.

**Comment by Jalpa-Ahalpara** [comment]
Thank you !! sir For Replay 
I was download ninja.exe from [https://github.com/ninja-build/ninja/archive/v1.9.0.zip]
Than after create a build folder and put it on to in 
and go to build/ directory (In CMD)and run "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat" this command it run successfully than after run "cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DUSE_SANDBOX=OFF .." it will give error

**Comment by Jalpa-Ahalpara** [comment]
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:120 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:120 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
