### ISSUE TITLE
Mismatch detected for 'RuntimeLibrary'

### ISSUE THREAD

**Issue by Jalpa-Ahalpara** [cztomczak/phpdesktop#258]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in app.obj	phpdesktop-chrome

**Comment by cztomczak** [comment]
You have to read carefully the build instructions and follow all of the instructions exactly as told. Looks like you're mixing Release and Debug configurations or using incompatible Visual Studio version.
