### ISSUE TITLE
Enable Speech sythesis

### ISSUE THREAD

**Issue by ReiPsalm** [cztomczak/phpdesktop#259]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

is there any way, i could Enable Speech synthesis on phpdesktop? or is there any plugins you can suggest to get this done somehow? i was wondering if any updates will be added, i hope speech synthesis will be one of it, thanks! and Cheers!

**Comment by cztomczak** [comment]
Pass the `--enable-speech-input` switch and enable Google API keys. Note that there is a limit of 50 queries per day.
