### ISSUE TITLE
Error MSB3073:VCEnd existed with code 1

### ISSUE THREAD

**Issue by Jalpa-Ahalpara** [cztomczak/phpdesktop#260]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

The system cannot find the file specified.
          0 file(s) copied.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "copy /y "C:\Users\harsh\OneDrive\Desktop\Jalpa\phpdesktop-master\src\settings.json" "C:\Users\harsh\OneDrive\Desktop\Jalpa\phpdesktop-master\src\Release\settings.json" 

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code 1.

**Comment by cztomczak** [comment]
Please stop creating any more issues. You have to choose Release configuration as instructions say.
