### ISSUE TITLE
Laravel Ajax Put Method Returning 401

### ISSUE THREAD

**Issue by tooshort26** [cztomczak/phpdesktop#262]
I'm getting 401 unauthorized each time I request using PUT method with Ajax.

![image](https://user-images.githubusercontent.com/54329064/63406721-47404200-c41d-11e9-81ad-a7cc85082845.png)

**Comment by cztomczak** [comment]
Not supported. Duplicated of #140.

**Comment by tooshort26** [comment]
Thanks!
