### ISSUE TITLE
HTA + PHP?

### ISSUE THREAD

**Issue by nurky** [cztomczak/phpdesktop#265]
I have downloaded the MSIE Minimal build and HTA does not seem to work there, is there a flag to force a behavior like this? I used to make great looking apps using HTA as frontend (HTML,CSS,JS) and PHP as backend (posts, images, videos, messages, etc)

PHPDesktop MSIE:
![image](https://user-images.githubusercontent.com/55628546/67132886-9e3e7980-f20a-11e9-9163-26a4dfc900e0.png)

Actual HTA:
![image](https://user-images.githubusercontent.com/55628546/67132884-9bdc1f80-f20a-11e9-88c1-b5af35f08f81.png)

I want to create notepad-like application using HTA for the frontend (especially themes and syntax highlighting) and PHP as the main program code (reading from files, writing to files, etc)

...yes I could do this in Electron but I'm really stuck with PHP because It's very similar to C++ and I like that.

**Comment by cztomczak** [comment]
Does HTA work if you run it from inside IE browser? See https://github.com/cztomczak/phpdesktop/wiki/MSIE-engine

**Comment by cztomczak** [comment]
What OS and MSIE version? Check MSIE version using javascript in phpdesktop.

**Comment by nurky** [comment]
OS: Latest Windows 10 (Version 1903 - Build 18362.418)
MSIE: Internet Explorer (Version 11.418.18362.0)

Thing is that for HTA Apps to work the filename needs to have an extension of ".hta"
The process responsible for running HTA files is mshta.exe (Microsoft HTML Application) 

I imagined that loading such file inside PHP-MSIE would work but I think the application does not have the same inner workings as mshta to actually read .HTA and the <HTA:Application /> properties in order to disable things like borders, window shadows, title bars, etc.

But yet the window looks very the same as in HTA, perhaps there is a way to pass .HTA files as PHP files including the <HTA:Application /> tag so that the application is tricked into thinking it's parsing HTA file and thus giving the user control over the UI of the application.

![image](https://user-images.githubusercontent.com/55628546/67145371-70e0e280-f281-11e9-854f-6dc76f02c3ae.png)


Having such thing working can be truly amazing, because It not only provides us to have control of the system files outside the application through PHP but we can also theme our applications as we desire.

Here is a small project I did months ago, this is pure HTA with HTML/CSS/JS & of course PHP.
![image](https://user-images.githubusercontent.com/55628546/67145431-efd61b00-f281-11e9-9a6b-7145d5843b67.png)

The UI you see is completely handled by HTML, CSS and JavaScript!

**Comment by cztomczak** [comment]
Did you answer my question? Does HTA work if you run it from inside IE browser? If not then it's not possible to run it inside phpdesktop browser either, not without modifications in C++ code.

**Comment by nurky** [comment]
I've used PHP to pass the header Content-Type to be application/hta for which MSIE asks me if I want to open the application or not, upon opening the PHP code is executed as If I redirected to the program by default using HTA, but the problem now is how to get rid of the HTA app prompt, there has to be some flag inside the PHP-MSIE code that disables these security levels and brings them down to the HTA ones.

![image](https://user-images.githubusercontent.com/55628546/67146656-8825cd00-f28d-11e9-8930-ee1c2f3bb64c.png)
![image](https://user-images.githubusercontent.com/55628546/67146658-8a882700-f28d-11e9-8524-8450fbc51f92.png)

**Comment by nurky** [comment]
Or make an alternative application which starts the PHP server and then opens the HTA pointing to the web site of that server.

**Comment by cztomczak** [comment]
An HTA is executed using the program mshta.exe. MSIE browser control which PHP Desktop MSIE embeds doesn't support HTA. There are no plans to support HTA.
