### ISSUE TITLE
Can't access route from another computer

### ISSUE THREAD

**Issue by kechankrisna** [cztomczak/phpdesktop#266]
I tested and love it but one thing that I can not figure out is that, When I run my application, it seems like I have no way to allow other computer to get access into my local server. Example, I run this application as the restful api while have no internet connect but local network works fine then I want other computers still be able to access this restful api. Thank you in advance.

**Comment by mathewberry** [comment]
In your `settings.json` file you can set the web server `listen_on` to `["*", 0]` which will allow you to access your API from any IP address. 

I find it best to use a specific port aswell `["*", 53154]`, then you can open the CMD, type `ipconfig` and find your Default Gateway (e.g. `192.168.32.3`)
[https://github.com/cztomczak/phpdesktop/wiki/Settings#web_server](https://github.com/cztomczak/phpdesktop/wiki/Settings#web_server)

You should now be able to access over your local network using your default gateway and port (e.g. `192.168.32.3:53154/my-api-endpoint`).

If this doesn't work for you and your; computer, laptop or wireless adaptor is compatible with hostednetwork you could look into using this to host your own lan and have the computers connect but it requires you to connect each computer to your hostednetwork.

Let me know if this is helpful

**Comment by kechankrisna** [comment]
Thank you, it works fine now.
