### ISSUE TITLE
Update Chrome

### ISSUE THREAD

**Issue by Aiman-najeeb** [cztomczak/phpdesktop#270]
Please update chrome to a newer version

this version in windows is old and have some problems in rendering

it tried Vuetify but some things aren't rendering in the right way

so am waiting for the next versions of this project

**Comment by cztomczak** [comment]
There is an ongoing funding to update Chrome to version 80, you can contribute by making a donation. See Issue #227.

**Comment by cztomczak** [comment]
Every dollar counts. If only 10% of phpdesktop users would contribute just a few dollars we can easily make the goal.
