### ISSUE TITLE
Didn't connect with databse

### ISSUE THREAD

**Issue by kanishka5564** [cztomczak/phpdesktop#276]
Hello, I hosted my database on Online Server, How to connect this with it

**Comment by cztomczak** [comment]
I guess you need to change host from localhost to public ip address in script configuration.

**Comment by Dyp81** [comment]
Hello, i downloaded the 57.0 php 7.1 version and i tried adding php_pdo_sqlsrv_71_ts_x64 and php_dio-0.1.0-7.1.ts DLLs but it shows the could not find driver and driver not installed when i launch my programs. i added both DLLs in the ext folder and added entries in the ini file.
How can i do it

**Comment by cztomczak** [comment]
Your extension is not compatible (ts = thread safe). See knowlegdge base wiki page.
