### ISSUE TITLE
Error 500: Internal Server Error On windows 10

### ISSUE THREAD

**Issue by meetmec12** [cztomczak/phpdesktop#280]
Error 500: Internal Server Error
CGI program sent malformed or too big (>16384 bytes) HTTP headers: []

**Comment by cztomczak** [comment]
See https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#error-500-internal-server-error-cgi-program-sent-malformed-or-too-big-16384-bytes-http-headers
