### ISSUE TITLE
Don't know how to use Composer with PHPDESKTOP: Need to use Twilio

### ISSUE THREAD

**Issue by NJseo** [cztomczak/phpdesktop#281]
Hi, I am trying to use Twilio on my PHPDesktop application but it requires composer installed files and I just am not sure how to do this with PHPDESKTOP. Can you be of assistance?

**Comment by Garrcomm** [comment]
Download a `composer.phar` file from https://getcomposer.org/download/ and place it in the `php` directory.
Now, open a `cmd.exe` window and go to the folder where your php code is. There, execute:
```
C:\phpdesktop\php\php.exe c:\phpdesktop\php\composer.phar install
```
