### ISSUE TITLE
Twilio Needs SSL support but don't know how to enable

### ISSUE THREAD

**Issue by NJseo** [cztomczak/phpdesktop#282]
Need ssl support but don't know how to enable. Its a requirement of Twilio.

Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

**Comment by Garrcomm** [comment]
In de `php` folder (where `php.exe` exists), add a `php.ini` file with these contents:
```ini
[PHP]
extension_dir = "ext"
extension=openssl
```
This way, you can add all extensions available in the `php/ext` folder.
Is that folder empty? Download the full version of PHP at https://windows.php.net/download/

**Comment by emilthorne** [comment]
Yes, that part works. Thanks!

But i also need to enable the .pem-certificate with 
curl.cainfo="\php\extras\ssl\cacert.pem"
openssl.cafile="\php\extras\ssl\cacert.pem"

But I'm struggeling with the relative file paths here. 

When putting in an absolute path to the cacert.pem it works fine, but when trying to input a relative file path it fails to find the cacert.pem.
What relative root is used in phpdesktop? I can confirm that it's not relative to php or phpdesktop.exe, what is right here?

**Comment by Garrcomm** [comment]
According to the example ini file `php.ini-development` it should require an absolute path:
```ini
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =
```

You could work around this by using code:
```php
$pemFile = realpath(__DIR__ . '/../php/extras/ssl/cacert.pem');
ini_set('curl.cainfo', $pemFile);
ini_set('openssl.cafile', $pemFile);
```

In this case it doesn't matter that PHP Desktop is in play, this is configuring PHP like any other PHP instance.

**Comment by inventer88** [comment]
curl.cainfo & openssl.cafile path to cacert.pem file has to a Absolute path in php.ini
&
This does not work, 
```
$pemFile = realpath(__DIR__ . '/../php/extras/ssl/cacert.pem');
ini_set('curl.cainfo', $pemFile);
ini_set('openssl.cafile', $pemFile);
```

Curl with ssl is absolute necessity in many projects. I found a solution, 
put absolute path in php.ini for cacert.pem, for example "C://ApplicationConfig/cacert.pem" (or any other location like inside Documents folder)

Now, make your application into a setup executable using this free software below. 
**`https://jrsoftware.org/isdl.php`**
**During the installation using setup executable,  cacert.pem file can be copied to "C://ApplicationConfig/cacert.pem"; matching hardcoded cacert.pem location in php.ini**

Else, you will have to explain each user, to copy cacert.pem to specific location manually.
