### ISSUE TITLE
Visual Studio 2017/2019 support?

### ISSUE THREAD

**Issue by shanmukhateja** [cztomczak/phpdesktop#284]
Hi,

I tried opening the project solution in Visual Studio 2017 Community and I got default "This project is incompatible with this version of Visual Studio".

I tried using `vcvars64.bat` to compile `cefclient` and although it compiled and worked, I still can't compile `phpdesktop` with `msbuild`.

Could you consider upgrading the project to recent editions of Visual Studio like 2017 or 2019?

**Comment by cztomczak** [comment]
What if you right click on the project and choose "Reload project" or "Resolve errors" if you have such options?

**Comment by shanmukhateja** [comment]
Hi @cztomczak 

When I open the solution in VS 2017, it would show the following in Solution Explorer:
![err2](https://user-images.githubusercontent.com/43369891/93291851-d88d0e00-f801-11ea-8ed2-0cc83a38d2cd.PNG)


And when I tried "Reload project" and "Resolve errors", it would show this prompt and then nothing happens.
![err1](https://user-images.githubusercontent.com/43369891/93291934-ff4b4480-f801-11ea-9513-f038f3734daf.PNG)

There is no "migration report" generated in the solution directory. I don't know what else to do. VS isn't my area of expertise.
