### ISSUE TITLE
VCRUNTIME410.DLL

### ISSUE THREAD

**Issue by passariello** [cztomczak/phpdesktop#286]
For sure you knows ... but please, fix! :)

![Screenshot 2020-10-16 134241](https://user-images.githubusercontent.com/17809213/96307020-bbd92700-0fb5-11eb-9933-89e59104c86e.png)

**Comment by kmlpandey77** [comment]
PHP 7 requires "Visual C++ Redistributable for Visual Studio 2015" installed - download x86 version.

**Comment by cztomczak** [comment]
See notes for the release: https://github.com/cztomczak/phpdesktop/releases/tag/chrome-v57.0-rc

**Comment by passariello** [comment]
Thanks guys! ... Yes, I see! :)
