### ISSUE TITLE
Connecting phpdesktop to MS SQL Server

### ISSUE THREAD

**Issue by Mynameisnobo** [cztomczak/phpdesktop#288]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

Hello. My php and html code is connected to my MS SQL Server. I used phpdesktop and converted my code to .EXE but my program doesn't get any feedback from the server. My question is can phpdesktop be connected to SQL Server?

**Comment by cztomczak** [comment]
Yes, it can connect. Check if your sql server accepts connections from php desktop ip address.
