### ISSUE TITLE
shadow variable

### ISSUE THREAD

**Issue by maddin200** [cztomczak/phpdesktop#289]
/src/cef/client_handler.cpp line 142 

BrowserWindow* phpBrowser = GetBrowserWindow(cefHandle);
    if (phpBrowser) {
        // This block of code gets called for Main window & Devtools window.
        ASSERT(!phpBrowser->GetCefBrowser().get());
        if (!phpBrowser->GetCefBrowser().get()) {
            LOG_DEBUG << "SetCefBrowser() called in "
                            "ClientHandler::OnAfterCreated()";
            phpBrowser->SetCefBrowser(cefBrowser);
        }
    } else {
        // CEF popup browser.
        BrowserWindow* phpBrowser = new BrowserWindow(cefHandle, true);  // <-- shadow
        StoreBrowserWindow(cefHandle, phpBrowser);

**Comment by cztomczak** [comment]
I don't see a problem.
