### ISSUE TITLE
About File Extension 

### ISSUE THREAD

**Issue by dastaankhan06** [cztomczak/phpdesktop#300]
Questions should be asked on the forum:
https://groups.google.com/d/forum/phpdesktop

Hi sir i have download the files but its application file  extension is change its not working 
the  application file  extension is sln and all files has in another extensions

**Comment by cztomczak** [comment]
Looks like you've downloaded sources. The binaries link is [phpdesktop-chrome-57.0-rc-php-7.1.3.zip](https://github.com/cztomczak/phpdesktop/releases/download/chrome-v57.0-rc/phpdesktop-chrome-57.0-rc-php-7.1.3.zip)
