### ISSUE TITLE
phpdesktop chrome not working on postman

### ISSUE THREAD

**Issue by khushal-more** [cztomczak/phpdesktop#301]
Hello Team,
I am new to phpdesktop chrome. I simply created index.php file in www directory for simplicity  and modified settings.json file for static IP as well as port, it's working properly in phpdesktop screen as well as in browser(by navigating to IP with port). but when i try to hit the same request on Postman, then there is an issue for response. i have attached all screens for reference. may you pl checkout?
The reason for using Postman is that. we are going to make apis/services to be used by android/ios devices.

index.php
![Screenshot_1](https://user-images.githubusercontent.com/86946509/131796292-928ba26f-8509-473b-86d1-6040b77bc727.png)

settings.json
![Screenshot_2](https://user-images.githubusercontent.com/86946509/131796399-9c5d83a8-7147-41d7-9e42-ae6efb3e0dd1.png)

phpdesktop screen
![Screenshot_3](https://user-images.githubusercontent.com/86946509/131796542-174942d9-1424-4c54-bc33-6841243b8c06.png)

Chrome screen
![Screenshot_4](https://user-images.githubusercontent.com/86946509/131796710-7bf0d6ce-830d-416a-8a7a-f179b596484e.png)

Postman Bug Screen
![Screenshot_5](https://user-images.githubusercontent.com/86946509/131796869-702514c3-5364-476f-b0c4-1cea1246a92d.png)

**Comment by cztomczak** [comment]
PHP Desktop uses Mongoose web server. Maybe Postman doesn't understand one of the headers Mongoose sends. Or Mongoose doesn't understand some of the headers Postman sends. I suggest you compare what headers sends PHP Desktop vs other web server. Also what is "Error: Parse error". Is this error that Mongoose throws or Postman? Any other messages in php desktop logs?
