### ISSUE TITLE
Windows XP

### ISSUE THREAD

**Issue by JeanPaulLucien** [cztomczak/phpdesktop#306]
I look for Windows XP version and knew that version or Windows XP uses IE 6.0 engine. I know that to use Chrome on Windows XP is bad idea. There are Firefox and forks with big community and developer team.

**Comment by cztomczak** [comment]
Version 47 of phpdesktop runs on Win XP SP3: https://github.com/cztomczak/phpdesktop/releases/tag/chrome-v47.5-rc

**Comment by JeanPaulLucien** [comment]
@cztomczak 
Chromium (Chrome) 110+ is ready for Windows XP, Check my profile for info. Or you may try Firefox 90-91...
