### ISSUE TITLE
Linux build php-cgi shared library issue

### ISSUE THREAD

**Issue by mikeshiyan** [cztomczak/phpdesktop#310]
Hello! Linux Mint user here.

I downloaded and extracted `phpdesktop-linux-72.0.tar.gz`.
I cleared the `www` directory and put a single file there, named `index.php` and containing `Hello World!` (no php code).

When I open phpdesktop I see:

> Error 500: Internal Server Error
> CGI program sent malformed or too big (>16384 bytes) HTTP headers: []

When I run `./php-cgi -i` (on the packaged php-cgi) I get:

> php-cgi: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory

I saw a mention of the "libpq5" in the [release notes](https://github.com/cztomczak/phpdesktop/releases/tag/linux-v72.0). But if I understood correctly, that was only about mysqli-pgsql version of the php-cgi binary.

Update: I found a solution and fixed the issue by installing the missing shared library: `sudo apt install libpq-dev`

Is it possible to pack that library with phpdesktop?

**Comment by cztomczak** [comment]
Have you tried both 72.0 and 72.1? The release note is for 72.1, so try that version.

**Comment by mikeshiyan** [comment]
> Have you tried both 72.0 and 72.1? The release note is for 72.1, so try that version.

Unfortunately, I didn't try 72.1, only 72.0.

Anyway, I decided to use fresh PHP binaries, so I won't use packaged ones.
