### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by abbasmashaddy72** [cztomczak/phpdesktop#312]
Need Update PHP 8.x for phpdesktop

**Comment by redatlm** [comment]
i think you can simply download PHP 8 version and replace it by your PHP folder in PHP desktop chrome

**Comment by abbasmashaddy72** [comment]
Thanks I will Check it Out

**Comment by redatlm** [comment]
i tried this from PHP 7.1 (default PHP version) to php 7.4.12 version and it work perfectly.
Now i have 3 softwares using PHP DESKTOP CHROME and there is no bugs for windows 7, 10 and 11.
I recommend you to use it.

**Comment by zohaib87** [comment]
[Update the PHP Version ](https://github.com/cztomczak/phpdesktop/wiki/Knowledge-Base#php-interpreter--extensions)
