### ISSUE TITLE
Any version without chrome 

### ISSUE THREAD

**Issue by AskDesignTeam** [cztomczak/phpdesktop#314]
i want to use php desktop without chrome, i need to run only the server with cmd commands on silent mode, i want to delete all chrome files like "libcef.dll" to have a final small folder size server to deploy with my app

**Comment by cztomczak** [comment]
See https://github.com/cztomczak/phpdesktop/wiki/PHP-Desktop-MSIE-v1.14

**Comment by equinenigeria** [comment]
Hi cztomczak. I've been trying to convert php and laravel projects to desktop app. All my efforts doesnt work. 
First trouble is the project version supports php >=8.1
secondly, other projects output error. blocked by firewall exiting now. etc.

Do i have the opportunity to get your support to have this achieved. I have been on this for some years now. thank you

**Comment by DZunke** [comment]
@equinenigeria it is not really easy to do the chrome update yourself but for PHP there is not any problem to use a newer runtime. I have it in one of my offline running projects Makefile to utilize PHP 8.0 ... just search for the latest php nts download link and replace the runtime in the project to have PHP >= 8.1 running :) 

See here at target "phpdesktop":  https://github.com/DZunke/VDOLog/blob/v1.x/Makefile

**Comment by cztomczak** [comment]
Instructions on how to update PHP version bundled with PHP Desktop are available on the Knowledge Base wiki page.

**Comment by equinenigeria** [comment]
Thank you. Really appreciate
