### ISSUE TITLE
Unable to play local video

### ISSUE THREAD

**Issue by tuoyitian** [cztomczak/phpdesktop#319]
Videos like <video src="./abc.mp4"></video> not able to be played.

**Comment by tuoyitian** [comment]
like this:〈video src="./abc.mp4"〉

**Comment by jarnalyrkar** [comment]
Chromium Embedded Framework, which is used as the browser engine doesn't support MPEG-formats.

I had the same issue with mp3's, but I solved it by converting to OGG using ffmpeg.

**Comment by cztomczak** [comment]
Proprietary codecs like H264 / h265 can be supported by making a custom CEF build with special flags.
