### ISSUE TITLE
Compilation : 'OVERRIDE' : unknown substitution specifier

### ISSUE THREAD

**Issue by Prozax03** [cztomczak/phpdesktop#321]
Hello, I followed the link to build on Windows (https://github.com/cztomczak/phpdesktop/wiki/Build-on-Windows), but when compiling I have a lot of errors on the "override". [https://image.noelshack.com/fichiers/2023/27/5/1688682100-image-2023-07-07-001947469.png](url)

I try with cef 114

Thanks in advance for your help

**Comment by cztomczak** [comment]
You have to build with the supported CEF version.
