### ISSUE TITLE
Windows: PHP configuration misses support of GD graphics

### ISSUE THREAD

**Issue by belbernard** [cztomczak/phpdesktop#347]
The configuration of PHP on the current Windows version is poor compared with the MacOS version.
The main thing I am missing is the support  of GD Graphics  (which works on the MacOS version).
The command should contain the option "--enable-gd". (I am not sure this is all we need.)
I read that php was compiled On October 22, 2024.

**Comment by belbernard** [comment]
I feel a bit lost on windows.php.net/download/
I plan to choose V17 x86, but should it be "Thread Safe" or "Non Thread Safe"?
Then, should I download the "Zip" package and put its entire content into phpdesktop/php/ ?

**Comment by cztomczak** [comment]
Actually new phpdesktop binaries are 64 bit, so it should be 64 bit.
Yes, NTS = non thread safe.
If you need to customize it then you can build from sources.

**Comment by cztomczak** [comment]
I modified wiki page to download x64, not x86.

**Comment by belbernard** [comment]
Great, thank you! And which package? The "Zip"? Put its entire content into phpdesktop/php/ ?

**Comment by belbernard** [comment]
After installing "VS17 x64 Non Thread Safe" (PHP 8.4.1) I got the message at startup:

Error 500: Internal Server Error
CGI program sent malformed or too big (>16384 bytes) HTTP headers: []

Should I try an older version of PHP?

**Comment by cztomczak** [comment]
You probably copied it wrong. Check files dirs structure.

**Comment by cztomczak** [comment]
Run the php-cgi executable manually to see any errors. See wikipedia KB page for common issues.

**Comment by cztomczak** [comment]
@belbernard The https://github.com/crazywhalecc/static-php-cli project now supports cgi binary, except for Windows from what I read.
